### ISSUE TITLE
Rowing Machine?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#165]
One of my favourite high intensity / low impact _full_-body cardio activities in the gym is rowing!
When I visit the gym I end up doing around **`T10m`** of rowing, 
usually **`T5m`** before weights and **`T5m`** at the end of workout.

Of all the exercise "_machines_" this is my favourite because it's a full-body workout. 🚣 
Aaaaandd ... if I can get my kids into it _early_, they can get a **_full_ scholarship** to Oxford or Cambridge: 
https://oubc.org.uk/row-for-oxford/ 😜

**Comment by LuchoTurtle** [comment]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/17494745/210056805-1de231c3-0ba3-4053-af25-76bf82b0cf24.png">

**Comment by nelsonic** [comment]
@LuchoTurtle this is the rowing machine I was thinking of getting:
https://firstdegreefitness.com/shop/fluidrower/apollo-pro-v/
![image](https://user-images.githubusercontent.com/194400/210056658-60892180-9264-4d86-8add-4b3d29d2b8c0.png)

The design of this _really_ appeals to me:
![image](https://user-images.githubusercontent.com/194400/210063705-4d94718e-745f-48d9-a3ba-5fcf3b495e2d.png)


https://www.olx.pt/d/anuncio/aparelho-de-profissional-de-remo-indoor-gua-IDHgWmd.html
![image](https://user-images.githubusercontent.com/194400/210056874-90275809-9841-488b-bcec-9e4a0c109de5.png)

![image](https://user-images.githubusercontent.com/194400/210063678-25ae7cf6-9ab7-448f-af61-c93030bf5d0f.png)

As you know, I'm a _huge_ fan of buying things second-hand because it puts money back into the hands of people who _need_ it and doesn't use any more natural resources ...

**Comment by nelsonic** [comment]
@LuchoTurtle please find out from your rowing friends if “money is no object” what rower they would buy for their personal home gym. 
(Obvs we’re not going to buy the Dubai ~ gold & diamonds ~ version, but you get what I mean … we aren’t buying something cheap/crappy that nobody will enjoy using!)

so would people go for the “tried and tested” Concept 2 or something a bit more niche like a water rower that simulates fluid dynamics better? 💭

**Comment by nelsonic** [comment]
Concept2 with **`PM5`** monitor are the ones I'm most used to in Gyms in the UK.

https://myfitness-room.com/product/concept2-model-e-with-monitor-pm5-gray/
![image](https://user-images.githubusercontent.com/194400/210062800-57b77b03-651b-4b9c-8974-ad2890d9ffbd.png)

But the Fluid (water) rowers look great and are supposed offer a more "natural" feel ... 
https://myfitness-room.com/product/life-fitness-row-hx-rowing-machine/
![image](https://user-images.githubusercontent.com/194400/210062747-d473e057-fe80-4dbf-9940-5f25cc2f66d9.png)

I _wonder_ what the long-term durability of the water tank ... ⏳ 
And if any reason the tank were to break/crack (because of sun exposure, water and friction) what the process to repair/replace it would be ... 💭 
By contrast the Concept2 design has been around for _decades_: https://en.wikipedia.org/wiki/Concept2
So it's _far_ more likely that we can source parts if something breaks. 🛒 

I find the wooden design aesthetic of water tank rower _far_ more appealing ...
But I think ultimately we need to make this decision based on practicality not aesthetics.
I consider the Concept2 to be the "Lenovo" (IBM ThinkPad) of rowers in terms of reliability.

_Very_ keen to hear back from you and your rowing friends on this. 💭

**Comment by nelsonic** [comment]
This is the model @LuchoTurtle shared above:
https://myfitness-room.com/product/concept-2-rowerg-new-model-with-pm5/
![image](https://user-images.githubusercontent.com/194400/210099189-11f5ef4d-e8cb-4cf9-8726-ccd2414ab364.png)

**Comment by nelsonic** [comment]
`WaterRower` Natural:
https://myfitness-room.com/product/waterrower-natural-fresno-water-rowing/
![image](https://user-images.githubusercontent.com/194400/210099557-06df5a59-55a5-4406-aa79-585cd81cb054.png)

**Comment by nelsonic** [comment]
I'm unable to verify the reliability of https://myfitness-room.com online. 
https://www.google.com/search?q=review+myfitness-room.com

All the google results are for [myfitnesspal-room.com](https://www.google.com/search?q=review+myfitnesspal-room.com&sa=X&ved=2ahUKEwjd_s32gqL8AhUvU6QEHcZ2CWQQ7xYoAHoECCcQAQ&cshid=1672426757139345)

![image](https://user-images.githubusercontent.com/194400/210103888-f48a0591-3c45-45e3-8b99-91a62be88790.png)

On this basis, I don't feel super comfortable sending them **`€895`** or **`€695`** no matter how much cheaper than RRP they are selling the devices. If it's too good to be true, it probably is. 💭 
I've heard plenty of horror stories of people finding a "bargain" on FB marketplace,
sending over the cash through some basic-looking e-commerce website,
and _never_ seeing the money again. 💸 
Ask Andy about his infamous shoe rack ... 😕 

Still trying to decide if we should get a Concept 2 or WaterRower ... 🤷‍♂️

**Comment by nelsonic** [comment]
The **`RowErg Concept 2`** rowing machine with `PM5` monitor costs **`€1250`** ***`new`***. 
https://www.decathlon.pt/p/maquina-de-remo-d-pm5-concept-2/_/R-p-X8361558
![image](https://user-images.githubusercontent.com/194400/212920353-a7c065f4-dead-4596-9a5d-5b027a8e8fcb.png)

There's a second hand on in "excellent condition" on in Porto/Matosinhos that looks good:
https://www.olx.pt/d/anuncio/remo-indoor-concept-2-IDHwbUg.html
![image](https://user-images.githubusercontent.com/194400/212922005-bb75e463-f8af-469a-976f-151b32db0b0c.png)

I've contacted the seller to ask if we can go view it. 💬

**Comment by nelsonic** [comment]
@LuchoTurtle any word back from your rowing friends? 💭

**Comment by LuchoTurtle** [comment]
No word 🤷

**Comment by nelsonic** [comment]
I know it’s expensive, but I feel like it’s a *very* nice piece of equipment for our @home gym …  💭🚣‍♀️

**Comment by LuchoTurtle** [comment]
Closing this as the machine's already purchased.

**Comment by nelsonic** [comment]
Thanks again for going out to test and collect it. 👌
