### ISSUE TITLE
Today's Batch of Green Juice

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#58]
As always, the experiment "stats" logged in my ***spreadsheet***:
![image](https://cloud.githubusercontent.com/assets/194400/22621063/901bee5c-eb12-11e6-933a-df80f28898eb.png)

![juice-01-shopping-baskets](https://cloud.githubusercontent.com/assets/194400/22621187/71d60e48-eb15-11e6-9e9a-df45b6118349.JPG)

![juice-00-supermarket](https://cloud.githubusercontent.com/assets/194400/22621192/96c5336e-eb15-11e6-9fd3-b0f78277ce0e.JPG)
**Note**: the milk is _definitely_ not mine!!! Milk is _baaaad_ ... http://www.peta.org/living/food/reasons-stop-drinking-milk/

Receipt:
![juice-receipt](https://cloud.githubusercontent.com/assets/194400/22621213/0cb08916-eb16-11e6-820e-ef3de393877a.JPG)
(_obviously not all these ingredients are for juicing..._)

I cycle to/from the shops to save on delivery costs and get some exercise!
![juice-00-bike-pannier](https://cloud.githubusercontent.com/assets/194400/22621195/a75b3b56-eb15-11e6-8a01-f4a50ff2af18.JPG)

_Obligatory_ selfie. 😉 
![juice-nelson-cycling](https://cloud.githubusercontent.com/assets/194400/22621196/acdffa4e-eb15-11e6-9e9e-1c15e0152839.JPG)

Don't worry mom, I was stopped at a red light ...
![stopped-at-red-light](https://cloud.githubusercontent.com/assets/194400/22621218/50c37ad2-eb16-11e6-9414-92070d77a08f.JPG)

This is the produce I'm going to consume in the next 48h ...
![juice-02-counter](https://cloud.githubusercontent.com/assets/194400/22621198/b6accf20-eb15-11e6-80e3-a2bd002f844a.JPG)
(_Minus the nuts, carrots, cabbage, hoummus and sweet potato which are for later in the week!_)

Let's get _juicing_!!
![juice-cucumber-counter](https://cloud.githubusercontent.com/assets/194400/22621199/bad56760-eb15-11e6-80f9-10be125970ec.JPG)

Cucumber is _incredibly_ juicy!
![juice-jug-full](https://cloud.githubusercontent.com/assets/194400/22621200/c07c2726-eb15-11e6-8db3-5d65d74bfe24.JPG)
(_it's also super healthy, cheap and refreshing!!_)

I poured the juice from the jug into our giant Soup Pot to mix it up before poring into bottles:
![juice-pot-and-pulp](https://cloud.githubusercontent.com/assets/194400/22621201/c74a88e0-eb15-11e6-8c09-16bb0ea2a12a.JPG)
And kept the pulp for composting.

While doing "_product research_" I purchased a few bottles of juice, tried the product and washed/kept the bottles for re-use:
![juice-00-empty-bottles](https://cloud.githubusercontent.com/assets/194400/22621202/cf4ac082-eb15-11e6-896f-5383a6538f54.JPG)

Poured the juice from the pot into a Pyrex measuring jug because it's easier to pour into bottles"
![juice-00-pouring](https://cloud.githubusercontent.com/assets/194400/22621208/ef7a9378-eb15-11e6-9ba3-a7adf4892e43.JPG)

Made **6 Litres** of Green Juice:
![juice-00-bottles](https://cloud.githubusercontent.com/assets/194400/22621209/f49733a2-eb15-11e6-96da-2f12ac090219.JPG)

This is my Juice (_fast_) for the next 48h:
![juice-00-fridge-shelf](https://cloud.githubusercontent.com/assets/194400/22621212/f95011de-eb15-11e6-8fea-17ea43650ec0.JPG)

If you're wondering why the price of the Broccoli in the spreadsheet does not match up to that on the receipt, it's because I had bought two heads of Broccoli during the week which I used in the juice. Also, had a few extra cucumbers and celery which I bought at Sainsburry's which I added at the cost.

Also, the receipt includes a few other groceries which aren't juice related 
+ pink lady apples for @katbow 😉 
+ houmous, crunchy salad, straberries, raspberries, peas and carrots for @iteles 
+ sweet potato and savoy cabbage for my soup during the week... 

I think next time I will _separate_ the Juice bill from the rest of the groceries so it's clearererer.

**Comment by katbow** [comment]
Yay ❤️ pink lady apples!

Also that's some tasty looking green juice, so healthy! 💪 🍏 💚

**Comment by nelsonic** [comment]
Just wanted to capture the process. no need to keep this issue open any longer. 👍 
Juice fast going well. bit hungry tho... 😜 
So _Lucky_ I can afford to restore my health ... 🍀 
though **£5.32/day** isn't _that_ expensive... 💸 
(DWYL) `#SummerIsComming` ☀️  🎉

**Comment by carolrmc** [comment]
Why juice and not smoothie?

**Comment by nelsonic** [comment]
@carolrmc have you ever tried to consume **7.5kg** of **Veg** in **72h**...? 😜 

I **_prefer_ smoothies**. but they are a **_lot_ more filling**. which means you can **consume less** of them.
(_this is great if you are on a budget ... 2 Litres of Mixed Berries & Greens Smoothie is £3.5 which is a decent chunk cheaper than 2L of Green Juice and the blender is also **much** faster/easier to clean!_)

> The objective of the Juice Fast/Detox is to consume as **_many_ nutrients as possible**
and replenish all cells in your body while clearing out your digestive system...

Also, when I make a Greens + Berries smoothie it's typically 450g (_one package_) of Berries and about 200g of Greens (_usually spinach and kale_) so the ratio of greens to fruit is 1:2 
when I'm juicing I put in a few apples to not *hate* the taste of my juices but the ratio is typically 1kg of (_not very sweet "budget"_) Apples for 7.5kg of Vegetables (_see the spreadsheet/table at the top of this page..._) that 7:1 ratio is _crucial_ because I'm getting _way_ more greens for every gram of sugar. Which means my body is in "Ketosis" see: https://en.wikipedia.org/wiki/Ketosis ...

Green smoothies are great for "long-term" health _maintenance_ because they are filling and nutrient/fibre dense. But for short-term "detox" Green Juice is better. I have a ***lot*** of detoxing to do... 😮  (_making good progress tho ... haven't had pizza or IceCream this year...!!_)

See: https://github.com/dwyl/health/issues/60

**Comment by carolrmc** [comment]
Wow! 9kg of vegetables every day is a heck of a lot of veg!
Do you ever put ingredients like tomato or courgets into your juice? How
often do you juice?.... time is a real issue for me and I usually make
smoothies for two days at a time. I do admit that although I put in
cucumber and celery with my spinach, romaine lettuce and kale, I also put
in far too much fruit to make it sugarless!! 🙁
Not eating at all is really hard for me... although this week I've managed
rather well but not for the right reasons.🤒 Also keeping hydrated ... it's
hard in the winter to get excited about H2O.
What do you consider short term? you've been going at this for ages!

Please attach spread sheet- couldn't see it

**Comment by nelsonic** [comment]
@carolrmc it's roughly ***2.5kg*** of veg ***per day***.
I would have a _really_ hard time _eating_ more than One Kilo of veg in a day...
(_unless it was roast veg which I seem to have an insatiable appetite for, wonder why!!_)
So this is _by far_ the most effective way of getting _all_ the plant-based nutrients/vitamins. ✅ 

When I'm doing a "juice fast" I usually make about 6L which lasts me 3 days.
I compliment my green juice with 1-2L of Cold Green Tea and 1-2L of Lemon Water.
For a total of between 4 - 6L of liquid per day. And that's it. No snacks or food.
The first day of a juice fast is "OK" ... still got the "_excitement_" of trying to be healthy...
the second day is "***torture***" because your body is detoxing and ***all*** you can think about is food (_sugary, fatty, starchy, glutinous "food" ... which as we **all know** isn't **real food**!_)
but if you can make it through the second day (_by sleeping off the "cravings" ... when ever you feel a craving have a glass of water or juice and connect with your body, if you're feeling tired, take a nap, this is why it's good to start your fast on a Friday/Saturday so you have the weekend to sleep!!_) ...
if you can _make_ it through the ***second day*** you will feel _much_ better by the third day.
Fasting will _not_ "_kill you_". If anything you will begin to burn fat which will give you a _whole_ other level of energy and mental clarity ... if by the 5th day you are feeling like you want something to _eat_ have something healthy don't have a burger an chips as you will just _ruin_ all your "_hard work_"... 
I will be making a new batch of juice tomorrow morning and will continue logging my stats in my spreadsheet. I can _share_ it with you if you're interested. there is a "_screenshot_" of the spreadsheet in the top of this issue showing cost and extraction quantities, can you see it? 

trust me there is "_method to the madness_"... I'm not "starving" for _fun_ there's a _specific reason_!
I expect to be a _different_ person by April and ***10 Years Younger*** by August. 😉

**Comment by nelsonic** [comment]
**£2.35/Litre** using "store bought" ingredients:
![image](https://cloud.githubusercontent.com/assets/194400/23837548/264c47ec-0782-11e7-8a66-2ea85cb8f78b.png)

_Eight_ of my "Five-a-Day"... 😉

**Comment by carolrmc** [comment]
Sounds amazing. Interesting to note that Broccoli doesn't render much
juice.
You maust be so incredibly healthy with all those micro phytonutrients, and
exercise!
Well done!

**Comment by nelsonic** [comment]
Avoiding juice for the foreseeable future (_especially containing fruit_) because _far_ to high in carbs!!
Instead going with Nuts: https://github.com/dwyl/health/issues/84
