### ISSUE TITLE
Brain Health Assessment: Discover Your Brain Type

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#97]
https://brainhealthassessment.com/
via: https://youtu.be/AUBe5vkPPlY 11 Risk Factors That Destroy Your Brain | Dr. Daniel Amen

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/51023200-42113f80-157e-11e9-8aae-53699b6d2cf2.png)

![image](https://user-images.githubusercontent.com/194400/51023217-48072080-157e-11e9-94b2-d14ea9e62f4d.png)

![image](https://user-images.githubusercontent.com/194400/51023220-4b9aa780-157e-11e9-91cd-7626355dd0de.png)

![image](https://user-images.githubusercontent.com/194400/51023232-52291f00-157e-11e9-889e-75b8d3a59b34.png)

![image](https://user-images.githubusercontent.com/194400/51023243-5a815a00-157e-11e9-9398-e250f7a55e6e.png)

![image](https://user-images.githubusercontent.com/194400/51023256-65d48580-157e-11e9-8724-a5edea0a1ef7.png)

![image](https://user-images.githubusercontent.com/194400/51023265-6d942a00-157e-11e9-95f7-21b8e2acb973.png)

![image](https://user-images.githubusercontent.com/194400/51023287-797fec00-157e-11e9-8ca3-95d8abefb6ca.png)

![image](https://user-images.githubusercontent.com/194400/51023295-800e6380-157e-11e9-86a8-a44af8158f2f.png)

![image](https://user-images.githubusercontent.com/194400/51023319-90bed980-157e-11e9-942c-1fd187d68880.png)

![image](https://user-images.githubusercontent.com/194400/51023324-95838d80-157e-11e9-8448-3a638ab5bdcb.png)

![image](https://user-images.githubusercontent.com/194400/51023345-9fa58c00-157e-11e9-9ebb-c6b03328ebd1.png)

![image](https://user-images.githubusercontent.com/194400/51023364-a59b6d00-157e-11e9-8f53-73842ba644c0.png)

![image](https://user-images.githubusercontent.com/194400/51023376-ab914e00-157e-11e9-9e9e-59d6f509ebe9.png)

![image](https://user-images.githubusercontent.com/194400/51023383-b2b85c00-157e-11e9-953c-344502c312e6.png)

![image](https://user-images.githubusercontent.com/194400/51023394-b9df6a00-157e-11e9-8bb5-85533cd6a534.png)

![image](https://user-images.githubusercontent.com/194400/51023400-bf3cb480-157e-11e9-951f-d0ff7ffec820.png)

![image](https://user-images.githubusercontent.com/194400/51023418-cc59a380-157e-11e9-8f47-8b17e5f39b59.png)

![image](https://user-images.githubusercontent.com/194400/51023451-dda2b000-157e-11e9-8516-33335504ab75.png)

![image](https://user-images.githubusercontent.com/194400/51023459-e2676400-157e-11e9-81d4-962db1d5e257.png)

![image](https://user-images.githubusercontent.com/194400/51023471-ea270880-157e-11e9-9f04-07fb59e1439f.png)

![image](https://user-images.githubusercontent.com/194400/51023487-ef845300-157e-11e9-8b6a-d10507d6fdea.png)

![image](https://user-images.githubusercontent.com/194400/51023500-f90dbb00-157e-11e9-8bab-21f2061c8d24.png)

![image](https://user-images.githubusercontent.com/194400/51023509-ff039c00-157e-11e9-9d53-49dda455e863.png)

![image](https://user-images.githubusercontent.com/194400/51023527-0aef5e00-157f-11e9-91ea-00c3e51dbec4.png)

![image](https://user-images.githubusercontent.com/194400/51023548-16db2000-157f-11e9-9d7c-04cfaae53d56.png)

![image](https://user-images.githubusercontent.com/194400/51023537-117dd580-157f-11e9-91ba-672fb85fa836.png)

![image](https://user-images.githubusercontent.com/194400/51023584-29555980-157f-11e9-973c-82a607b12da7.png)

![image](https://user-images.githubusercontent.com/194400/51023599-3114fe00-157f-11e9-88d9-90130f835607.png)

![image](https://user-images.githubusercontent.com/194400/51023607-35411b80-157f-11e9-8273-688703525768.png)

![image](https://user-images.githubusercontent.com/194400/51023614-38d4a280-157f-11e9-98dc-f8a8c03ec19c.png)

![image](https://user-images.githubusercontent.com/194400/51023621-3d995680-157f-11e9-96b6-b719d8f8cdae.png)

![image](https://user-images.githubusercontent.com/194400/51023640-4427ce00-157f-11e9-8821-69605ab09b76.png)

![image](https://user-images.githubusercontent.com/194400/51023653-48ec8200-157f-11e9-8419-d914e7d1bebb.png)

![image](https://user-images.githubusercontent.com/194400/51023659-4ee26300-157f-11e9-803e-d3f58228e636.png)

![image](https://user-images.githubusercontent.com/194400/51023666-530e8080-157f-11e9-9754-9c59e996d72b.png)

![image](https://user-images.githubusercontent.com/194400/51023680-59046180-157f-11e9-9ba1-ce8c2d4c1116.png)

![image](https://user-images.githubusercontent.com/194400/51023692-60c40600-157f-11e9-9b0c-f6c15713f557.png)

![image](https://user-images.githubusercontent.com/194400/51023705-69b4d780-157f-11e9-980e-a070866720c4.png)

![image](https://user-images.githubusercontent.com/194400/51023714-6faab880-157f-11e9-8c45-bb4cc3e300b6.png)

![image](https://user-images.githubusercontent.com/194400/51023728-7802f380-157f-11e9-81f5-1ce0f5e61c3f.png)

![image](https://user-images.githubusercontent.com/194400/51023736-7c2f1100-157f-11e9-9185-75ec701b641c.png)

![image](https://user-images.githubusercontent.com/194400/51023749-86e9a600-157f-11e9-8ee5-181b74d2f07b.png)

After I've spent 7 minutes answering questions they ask for an email address to see the results!! 😠 

![image](https://user-images.githubusercontent.com/194400/51023762-91a43b00-157f-11e9-9d23-2d52e4615f45.png)

![image](https://user-images.githubusercontent.com/194400/51023825-c2847000-157f-11e9-88c1-aea37cb09629.png)

looks like a "fake" email address is fine as the next screen allows you to download a PDF:

![image](https://user-images.githubusercontent.com/194400/51023913-0a0afc00-1580-11e9-9237-b3030c001cc4.png)

![image](https://user-images.githubusercontent.com/194400/51023955-2ad35180-1580-11e9-8ff5-8f3912e87dbb.png)

[BrainHealthAssessment-Report.pdf](https://github.com/dwyl/health/files/2748869/BrainHealthAssessment-Report.pdf)

![image](https://user-images.githubusercontent.com/194400/51024025-59512c80-1580-11e9-873f-a26b66ac2fdf.png)

# Now Buy These Supplements ... 🙄 💸 

![image](https://user-images.githubusercontent.com/194400/51024048-6a9a3900-1580-11e9-9128-98d38bb30d86.png)

![image](https://user-images.githubusercontent.com/194400/51024065-7554ce00-1580-11e9-9efc-0137351c2107.png)
https://youtu.be/ZKQ2InHCTNg

# Want 1-on-1 Coaching? That'll Be $6k

![image](https://user-images.githubusercontent.com/194400/51024160-a59c6c80-1580-11e9-898a-b64510a18179.png)

# $99 / Month for 60 Months!! 😮 

![image](https://user-images.githubusercontent.com/194400/51024188-b51bb580-1580-11e9-8abc-a2c4c680b046.png)

Hmm ... let me think about that ... No!

**Comment by nelsonic** [comment]
Closing as not particularly relevant or helpful; this is just a lead qualifier / sales funnel ... 😞

**Comment by iteles** [comment]
![image](https://user-images.githubusercontent.com/4185328/51174342-7b63eb00-18af-11e9-9e39-e768e013476a.png)

![image](https://user-images.githubusercontent.com/4185328/51174429-ac442000-18af-11e9-98c9-d91316b81fb8.png)

[BrainHealthAssessment-Report.pdf](https://github.com/dwyl/health/files/2759153/BrainHealthAssessment-Report.pdf)


Meh.
